.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. kolocryptocoin_qt test_kolocryptocoin_qt
clean: FORCE
	$(MAKE) -C .. kolocryptocoin_qt_clean test_kolocryptocoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_kolocryptocoin_qt_check
kolocryptocoin-qt kolocryptocoin-qt.exe: FORCE
	 $(MAKE) -C .. kolocryptocoin_qt
